services:
  ladesa-api:
    image: node:22
    user: node
    command: sh -c "tail -f /dev/null"
    container_name: ladesa-api
    working_dir: /ladesa-api
    depends_on:
      - ladesa-api-db
    networks:
      - ladesa-net
    ports:
      - 3701:3701
      - 9229:9229
    volumes:
      - ../../:/ladesa-api
      - ./volumes/uploaded:/container/uploaded
    environment:
      - STORAGE_PATH=/container/uploaded
    env_file:
      - .env

  ladesa-api-db:
    image: bitnami/postgresql:15
    container_name: ladesa-api-db
    volumes:
      - 'ladesa-api-db-data:/bitnami/postgresql'
      # - './volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    networks:
      - ladesa-net
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .db.env

networks:
  ladesa-net:
    external: true

volumes:
  ladesa-api-uploaded-files:
  ladesa-api-db-data:
