FROM node:22 AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY integrations/npm/api-client-fetch/package.json ./integrations/npm/api-client-fetch/

FROM base AS build-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --filter "@ladesa-ro/api-client-fetch" --frozen-lockfile

FROM build-deps AS build
COPY ./integrations/npm/api-client-fetch/ ./integrations/npm/api-client-fetch/
RUN pnpm run -r --filter "@ladesa-ro/api-client-fetch" generate:docs

FROM nginx:alpine AS runtime
COPY integrations/npm/api-client-fetch/nginx.conf /etc/nginx/nginx.conf 
COPY --from=build /app/integrations/npm/api-client-fetch/docs /var/lib/ladesa-ro/cr/docs-packages-npm-api-client-fetch/dist
EXPOSE 80