export * from "./turma_disponibilidade.entity"
export * from "./turma_disponibilidade_dia.entity"
export * from "./disponibilidade-professor.entity"
export * from "./disponibilidade-professor-dia.entity"
export * from "./diario-preferencia-agrupamento.entity"
export * from "./horario-gerado.entity"
export * from "./horario-gerado-aula.entity"
