export * from "./ambiente.repository"
export * from "./bloco.repository"
export * from "./campus.repository"
export * from "./cidade.repository"
export * from "./endereco.repository"
export * from "./estado.repository"
