services:
  sisgea-luna-backend:
    image: node:20
    user: node
    command: sh -c "tail -f /dev/null"
    container_name: sisgea-luna-backend
    working_dir: /container/code
    depends_on:
      - sisgea-luna-backend-db
    networks:
      # - traefik-net
      - sisgea-luna-net
    ports:
      - 3000:3000
    volumes:
      - ../../../../../libs:/sisgea/env-dev/libs
      - ../../:/container/code
    # labels:
    #   #
    #   - 'traefik.enable=true'
    #   - 'traefik.docker.network=traefik-net'
    #   #
    #   - 'traefik.http.routers.luna-api.entrypoints=main'
    #   - 'traefik.http.routers.luna-api.rule=Host(`luna.sisgha.com`) && PathPrefix(`/api/`)'
    #   - 'traefik.http.routers.luna-api.tls=true'
    #   - 'traefik.http.services.luna-api.loadbalancer.server.port=3000'
    #   #
    #   - 'traefik.http.middlewares.luna-api-strip.stripprefix.prefixes=/api'
    #   - 'traefik.http.middlewares.luna-api-strip.stripprefix.forceslash=false'
    #   - 'traefik.http.routers.luna-api.middlewares=luna-api-strip'
      #
    env_file:
      - .env

  sisgea-luna-backend-db:
    image: bitnami/postgresql:15
    container_name: sisgea-luna-backend-db
    volumes:
      - 'sisgea-luna-backend-db-data:/bitnami/postgresql'
      - './volumes/db/scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    networks:
      - sisgea-luna-net
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .db.env

networks:
  sisgea-luna-net:
    external: true
  # traefik-net:
  #   external: true

volumes:
  sisgea-luna-backend-db-data:
