name: 'API Integrations'

on:
  workflow_dispatch:
  push:
    branches:
      - 'development'
      - 'production'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integrations-codegen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build local image
        uses: docker/build-push-action@v6
        with:
          file: 'Dockerfile.service'
          load: true
          push: false
          tags: local-service-build
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: local-service-build
          options: |
            -v ${{ github.workspace }}/integrations/openapi-json:/var/ladesa-ro/wflow/tmp |
            -e OUT_FILE=/var/ladesa-ro/wflow/tmp/generated.json
          run: |
            npm run gen:openapi

      - name: Log git changes
        run: git status
