name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'production'
      - 'development'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        if: ${{ env.ENABLE_PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        if: ${{github.ref_name == 'development'}}
        uses: docker/build-push-action@v6
        with:
          push: ${{ env.ENABLE_PUSH_IMAGE == 'true' }}
          tags: ${{ secrets.REGISTRY_URL }}/api:development
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push
        if: ${{github.ref_name == 'production'}}
        uses: docker/build-push-action@v6
        with:
          push: ${{ env.ENABLE_PUSH_IMAGE == 'true' }}
          tags: ${{ secrets.REGISTRY_URL }}/api:production
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Dispatch infrastructure deploy workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.DEPLOY_OWNER }}/${{ env.DEPLOY_REPOSITORY }}/actions/workflows/${{ env.DEPLOY_WORKFLOW }}/dispatches \
            -d '{"ref":"${{env.DEPLOY_BRANCH}}","inputs":{}}'
