name: Generate Integrations

on:
  push:
    branches:
      - development

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  node-version: 22

jobs:
  generate-integrations:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Print Tag
        shell: bash
        run: echo ${{ github.ref_name }}

      - name: Install
        uses: ./.github/actions/prepare/install
        with:
          install-node: "true"

      - id: build-integrations
        name: Build integrations
        run: |
          pnpm run --filter "@ladesa-ro/api.internal.integrations" build

          if [[ (git diff --exit-code > /dev/null; echo $?) -eq 1 ]]; then
            git checkout -b ldsa-automated/generated-integrations;
            git commit -m "chore: generate integrations"
            echo "has_changes=true" >> "$GITHUB_OUTPUT";
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT";
          fi

      - name: Create pull request
        if: steps.build-integrations.outputs.has_changes == 'true'
        run: |
          gh pr create \
            -B development \
            -H ldsa-automated/generated-integrations \
            --title 'Merge ldsa-automated/generated-integrations into development' \
            --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
